[package]
name = "rust-sokoban"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.8.1"
mint = "0.5.9"
specs = { version = "0.18.0", features = ["specs-derive"] }
